import { readFileSync, writeFileSync } from 'node:fs';

// This list is the source of truth for cascade order. Keep components before
// their view-specific adaptations, and static style classes last.
const CSS_FILES = [
    // Core System Files
    'styles/variables.css',          // CSS custom properties and design system variables
    'styles/utilities.css',          // Scoped utility classes for layout, spacing, typography
    'styles/base.css',               // Basic styles, animations, card components, and layout
    
    // BEM Component Files
    'styles/task-card-bem.css',      // TaskCard component with proper BEM scoping
    'styles/task-inline-widget.css', // Inline task widget for editor with proper BEM scoping
    'styles/note-card-bem.css',      // NoteCard component with proper BEM scoping
    'styles/filter-bar-bem.css',     // FilterBar component with proper BEM scoping
    'styles/filter-heading.css',     // FilterHeading component with proper BEM scoping
    'styles/search-box.css',         // SearchBox component with proper BEM scoping
    'styles/modal-bem.css',          // Modal components with proper BEM scoping
    'styles/task-modal.css',         // Task dialog and action controls
    'styles/reminder-modal.css',     // Reminder modal component with proper BEM scoping
    'styles/device-code-modal.css',  // OAuth device-code modal
    'styles/date-picker.css',        // Enhanced date/time picker styling
    'styles/task-selector-with-create-modal.css', // TaskSelectorWithCreateModal component with proper BEM scoping
    'styles/file-selector-modal.css', // FileSelectorModal component with proper BEM scoping
    'styles/unscheduled-tasks-selector-modal.css', // UnscheduledTasksSelectorModal component with proper BEM scoping
    'styles/task-action-palette-modal.css', // TaskActionPaletteModal component with proper BEM scoping
    'styles/time-entry-editor-modal.css', // TimeEntryEditorModal component with proper BEM scoping
    'styles/relationships.css',  // RelationshipsWidget component with proper BEM scoping
    'styles/task-card-note-widget.css',  // TaskCardNoteWidget component with proper BEM scoping
    
    // BEM View Files
    'styles/task-list-view.css',     // TaskListView component with proper BEM scoping
    'styles/calendar-view.css',      // CalendarView component with proper BEM scoping
    'styles/advanced-calendar-view.css', // AdvancedCalendarView component with proper BEM scoping
    'styles/kanban-view.css',        // KanbanView component with proper BEM scoping
    'styles/agenda-view.css',        // AgendaView component with proper BEM scoping
    'styles/pomodoro-view.css',      // PomodoroView component with proper BEM scoping
    'styles/pomodoro-stats-view.css', // PomodoroStatsView component with proper BEM scoping
    'styles/stats-view.css',         // StatsView component with proper BEM scoping
    'styles/release-notes-view.css', // Release notes view typography
    'styles/settings-view.css',      // SettingsView component with proper BEM scoping
    'styles/field-manager.css',      // Modal field manager settings
    'styles/webhook-settings.css',   // Webhook settings UI with proper BEM scoping
    'styles/status-bar.css',         // StatusBar component with proper BEM scoping
    'styles/bases-views.css',        // Bases integration views (list and kanban)
    'styles/static-style-utilities.css' // Static style utility classes migrated from inline styles
];

const sections = CSS_FILES.map((path) => {
    const source = readFileSync(path, 'utf8');
    return `/* ===== ${path} ===== */\n${source.trimEnd()}`;
});
const css = `/* TaskNotes: generated by npm run build-css. Edit styles/ source files. */\n\n${sections.join('\n\n')}\n`;
writeFileSync('styles.css', css);
console.log(`Built styles.css from ${CSS_FILES.length} source files (${Buffer.byteLength(css)} bytes).`);
