import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync, existsSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load environment variables from .env file or process.env
// Priority: process.env > .env file
function loadEnv() {
	const envPath = join(__dirname, '.env');
	const env = {};

	// First, load from .env file if it exists
	if (existsSync(envPath)) {
		const envContent = readFileSync(envPath, 'utf8');
		const lines = envContent.split('\n');

		for (const line of lines) {
			const trimmed = line.trim();
			// Skip comments and empty lines
			if (!trimmed || trimmed.startsWith('#')) continue;

			const [key, ...valueParts] = trimmed.split('=');
			if (key && valueParts.length > 0) {
				env[key.trim()] = valueParts.join('=').trim();
			}
		}
		console.log('OAuth credentials loaded from .env file');
	}

	// Override with process.env values if they exist (for CI/CD)
	// Only load client_id (public, safe to bundle)
	// client_secret is NOT bundled for security reasons
	const envKeys = ['GOOGLE_OAUTH_CLIENT_ID', 'MICROSOFT_OAUTH_CLIENT_ID'];
	for (const key of envKeys) {
		if (process.env[key]) {
			env[key] = process.env[key];
		}
	}

	// Log what we have (but not the actual values for security)
	if (env.GOOGLE_OAUTH_CLIENT_ID) {
		console.log('✓ OAuth client IDs configured (Device Flow ready)');
	}

	return env;
}

const env = loadEnv();

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Plugin to import markdown files as strings
const markdownPlugin = {
	name: 'markdown',
	setup(build) {
		build.onLoad({ filter: /\.md$/ }, async (args) => {
			const text = readFileSync(args.path, 'utf8');
			return {
				contents: `export default ${JSON.stringify(text)}`,
				loader: 'js',
			};
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [markdownPlugin],
	define: {
		// Inject OAuth client IDs at build time for Device Flow
		// These are PUBLIC identifiers (safe to bundle)
		// client_secret is NOT bundled (security requirement)
		// Device Flow (RFC 8628) only requires client_id, no secret needed
		'process.env.GOOGLE_OAUTH_CLIENT_ID': JSON.stringify(env.GOOGLE_OAUTH_CLIENT_ID || ''),
		'process.env.MICROSOFT_OAUTH_CLIENT_ID': JSON.stringify(env.MICROSOFT_OAUTH_CLIENT_ID || ''),

		// DO NOT BUNDLE SECRETS - Security issue documented in OAUTH_CALENDAR_ISSUES.md
		// Users with licenses use Device Flow (no secret required)
		// Users without licenses provide their own credentials in settings
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
