name: Bug Report
description: Report a bug or issue with TaskNotes
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!

        Please fill out the details below. The more info you provide, the faster we can help. 

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please describe the bug and any relevant details.
    validations:
      required: true

