name: Question
description: Have a question about TaskNotes? We're here to help!
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We'd be happy to help! 
        Before you ask, it's worth checking the [documentation](https://callumalpass.github.io/tasknotes-docs/) to see if your question has already been answered.

  - type: textarea
    id: question
    attributes:
      label: What's your question?
      description: "Please provide a clear and concise description of your question."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Anything else to add?
      description: "Feel free to add any other context or screenshots that might be helpful."
