name: Release Obsidian Plugin

on:
  push:
    tags:
      - '*'

env:
  PLUGIN_NAME: tasknotes

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Update manifest version from tag
        run: |
          # Extract version from tag (removes 'v' prefix if present)
          VERSION="${GITHUB_REF#refs/tags/}"
          VERSION="${VERSION#v}"
          echo "Setting version to: $VERSION"

          # Update manifest.json with the tag version
          jq --arg version "$VERSION" '.version = $version' manifest.json > manifest.tmp
          mv manifest.tmp manifest.json

          # Verify the change
          echo "Updated manifest.json:"
          cat manifest.json

      - name: Install Dependencies
        run: npm install

      - name: Build Plugin
        env:
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          MICROSOFT_OAUTH_CLIENT_ID: ${{ secrets.MICROSOFT_OAUTH_CLIENT_ID }}
        run: |
          cat <<EOF > .env
          GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
          GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
          MICROSOFT_OAUTH_CLIENT_ID=${MICROSOFT_OAUTH_CLIENT_ID}
          EOF
          npm run build  # This includes CSS building via npm run build-css

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            main.js
            manifest.json
            styles.css
          draft: true
